version: '3'

volumes:
  sonarqube_data:
  sonarqube_exts:

services:
  sonarqube:
    image: sonarqube:10-community
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_exts:/opt/sonarqube/extensions

